name: test-actions

on:
  push:
    branches:
      - main
    paths:
      - src/*
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: hello
        run: echo Hello, world!

      - name: use python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: run my script
        run: python3 hello.py
